### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by yash19sinha** [Gyanthakur/e_learning_website#1]
I would like to make the signup and login page more attractive and user friendly

**Comment by Kedarnath-Rothe** [comment]
please assign this issue to me... i will add login page

**Comment by Gyanthakur** [comment]
> please assign this issue to me... i will add login page

@Kedarnath-Rothe assigned to you

**Comment by Gyanthakur** [comment]
> I would like to make the signup and login page more attractive and user friendly

@yash19sinha add signup page

**Comment by priyanshu-gupta07** [comment]
@Gyanthakur can i work on this issue

**Comment by aarth01** [comment]
hey can you assign this issue to me i was  eagerly waiting to work on this.

**Comment by Gyanthakur** [comment]
@aarth01 go ahead
