### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Vani177** [Gyanthakur/e_learning_website#10]
Hey! 
I noticed a few typing errors and I would also like to improve the overall documentation of the file and make it more organized.
I would like to contribute to the repo by improving the things I listed above.
Please assign me this issue.
Thanks

**Comment by Gyanthakur** [comment]
@Vani177 assign to you

**Comment by Vani177** [comment]
thanks! could please assign it here as well?
![image](https://github.com/Gyanthakur/e_learning_website/assets/114817827/c22eaafb-5252-4b4f-b778-dbc781d422a9)
