### ISSUE TITLE
Made Changes in Login and Signup Page

### ISSUE THREAD

**Issue by aditya7302** [Gyanthakur/e_learning_website#2]

**Comment by aditya7302** [comment]
Please assign this issue to me

**Comment by Gyanthakur** [comment]
> Please assign this issue to me


In this issue, two contributors are already working. If you can propose a more attractive solution than the existing ones, please go ahead. **OR** you can create a new issue.

**Comment by aditya7302** [comment]
ok

**Comment by Gyanthakur** [comment]
@priyanshu-gupta07 create another issue

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by Kedarnath-Rothe** [comment]
hey, @Gyanthakur  can i work on 404 error pages!!!

**Comment by Gyanthakur** [comment]
> hey, @Gyanthakur can i work on 404 error pages!!!

@Kedarnath-Rothe assign to you 404

**Comment by priyanshu-gupta07** [comment]
@Gyanthakur i will try for another issue to but can u take a look at my pr for issue#2

**Comment by Gyanthakur** [comment]
> @Gyanthakur i will try for another issue to but can u take a look at my pr for issue#2

create another issue
