### ISSUE TITLE
fix: Validations in the SignUp Page 

### ISSUE THREAD

**Issue by Surya-V-28** [Gyanthakur/e_learning_website#6]
please assign me under the hacktober fest 

when i enter the details in signup of form 

instead of mobile number i gave the text , but it still works 

![image](https://github.com/Gyanthakur/e_learning_website/assets/102609082/61f23c98-86be-471e-9f30-a30657944aba)

I would like to work on this please assign me this

**Comment by Gyanthakur** [comment]
@Surya-V-28 assign to you
